class Autogenerated {
  int noOfLabels;
  String ordersMasterId;
  String partsInOrderId;
  String partsMasterId;
  String siteMasterId;
  String stockTypeId;
  String wareHouseInboundId;

  Autogenerated({this.noOfLabels,
    this.ordersMasterId,
    this.partsInOrderId,
    this.partsMasterId,
    this.siteMasterId,
    this.stockTypeId,
    this.wareHouseInboundId});
}