name: tvs_visibility
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build -number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.9+12

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  package_info: ^0.4.0+3
  rxdart: ^0.20.0
  kiwi: ^0.1.0
  barcode_scan: ^1.0.0
  shared_preferences: ^0.5.1+7
  fluttertoast: ^3.0.4
  jaguar_serializer:
  jaguar_retrofit: ^2.8.6
  webview_flutter: ^0.3.15+1
  loadmore: ^1.0.3
  font_awesome_flutter: ^8.4.0
  flutter_typeahead: ^1.4.1
  device_info: ^0.4.0+2
  dio: ^2.1.7
  intl:
  flutter_full_pdf_viewer: ^1.0.2
  path_provider: ^1.1.0
  printing: 2.1.8
  http:
  logger:
  url_launcher: ^5.2.5
  auto_size_text: ^2.1.0
  flutter_native_timezone: ^1.0.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  chopper_generator: ^2.0.0
  jaguar_retrofit_gen:
  jaguar_serializer_cli:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/privacy.html
    - assets/tvsscs.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans_Bold
      fonts:
        - asset: assets/OpenSans-Bold.ttf
    - family: OpenSans_BoldItalic
      fonts:
        - asset: assets/OpenSans-BoldItalic.ttf
    - family: OpenSans_ExtraBold
      fonts:
        - asset: assets/OpenSans-ExtraBold.ttf
    - family: OpenSans_ExtraBoldItalic
      fonts:
        - asset: assets/OpenSans-ExtraBoldItalic.ttf
    - family: OpenSans_Italic
      fonts:
        - asset: assets/OpenSans-Italic.ttf
    - family: OpenSans_Light
      fonts:
        - asset: assets/OpenSans-Light.ttf
    - family: OpenSans_LightItalic
      fonts:
        - asset: assets/OpenSans-LightItalic.ttf
    - family: OpenSans_Regular
      fonts:
        - asset: assets/OpenSans-Regular.ttf
    - family: OpenSans_Semibold
      fonts:
        - asset: assets/OpenSans-Semibold.ttf
    - family: OpenSans_SemiboldItalic
      fonts:
        - asset: assets/OpenSans-SemiboldItalic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
